import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/ui/styles/globals.css';
import Navbar from './ui/containers/GlobalContainers/Navbar/Navbar';
import Footer from './ui/containers/GlobalContainers/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="cinergia">
      <body className={`${inter.className} antialiased`}>
        {/*header with navigation bar */}
        <header className="fixed top-0 inset-x-0 z-50 w-full">
          <Navbar />
        </header>
        {children}
        {/* Footer component */}
        <Footer />
      </body>
    </html>
  );
}
